version: "3.9"
services:
  api:
    image: flawlesse/routes4life_api_local:latest
    volumes:
      - proj_files:/code
      - media:/media
    ports:
      - 80:8000
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - redis_cache
    
  db:
    image: flawlesse/routes4life_db_local:latest
    ports:
      - 8001:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_cache:
    image: redis:7.0.0
    entrypoint: ["bash", "-c", "redis-server", "--daemonize", "yes"]
    ports:
      - 6379:6379
    depends_on:
      - db

volumes:
  pgdata:
  proj_files:
  media: